on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - if: steps.setup-node.outputs.cache-hit != 'true'
        run: yarn install

  commitlint:
    needs: install
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn workspaces focus bhs

      - name: Validate current commit
        if: github.event_name == 'push'
        run: yarn commitlint --last --verbose

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    needs: install
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn workspaces focus @bhs/react
      - run: yarn workspace @bhs/react lint
      - run: yarn workspace @bhs/react typecheck
      - run: yarn workspace @bhs/react test-ci

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      base_url: ${{ steps.pages.outputs.base_url }}
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - uses: actions/configure-pages@v6
        id: pages

      - run: yarn workspaces focus @bhs/react
      - run: yarn workspace @bhs/react build-web
        env:
          BASE_URL: ${{ steps.pages.outputs.base_path }}

      - uses: actions/upload-pages-artifact@v5
        with:
          path: packages/bhs-react/dist
      - uses: actions/deploy-pages@v5
        id: deployment

  lint-e2e:
    needs: install
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn workspaces focus @bhs/e2e-web
      - run: yarn workspace @bhs/e2e-web lint

  e2e:
    needs: deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn workspaces focus @bhs/e2e-web
      - run: yarn workspace @bhs/e2e-web e2e --baseUrl=${{ needs.deploy.outputs.base_url }}
